Repository yiisoft/di, pull requests merged in 2021-11, with the labels that each got.

#274 Improve CompositeContainer error
  src/CompositeContainer.php
  src/CompositeNotFoundException.php
  src/NotFoundException.php
  tests/Unit/CompositePsrContainerOverLeagueTest.php
  tests/Unit/CompositePsrContainerOverYiisoftTest.php
  tests/Unit/NotFoundExceptionTest.php
Labels: type:enhancement

#276 Fix #275: Introduce parameters bag for container
  README.md
  src/CompositeContainer.php
  src/Container.php
  src/ContainerConfig.php
  src/ContainerConfigInterface.php
  tests/Benchmark/ContainerBench.php
  tests/Benchmark/ContainerMethodHasBench.php
  tests/Unit/AbstractCompositePsrContainerTest.php
  tests/Unit/CompositePsrContainerOverLeagueTest.php
  tests/Unit/CompositePsrContainerOverYiisoftTest.php
  tests/Unit/ContainerTest.php
  tests/Unit/ServiceProviderTest.php
  tests/Unit/YiisoftPsrContainerTest.php
Labels: type:enhancement

#278 Fix #256: Implement strict mode
  README.md
  src/Container.php
  src/ContainerConfig.php
  src/ContainerConfigInterface.php
  tests/Unit/ContainerTest.php
Labels: type:feature

#280 Fix #213: Document alternative metadata syntax
  README.md
Labels: type:docs

#281 Increase test coverage + minor refactoring
  composer.json
  phpunit.xml.dist
  src/DefinitionNormalizer.php
  tests/Unit/CompositeContainerTest.php
  tests/Unit/ContainerTest.php
Labels: status:code review

#282 Finalize `StateResetter` and add more exception into him + Add tests for 100% coverage
  composer.json
  src/StateResetter.php
  tests/Unit/ContainerTest.php
  tests/Unit/StateResetterTest.php
Labels: status:code review
